package ncurses


NCURSES_VERSION_MAJOR :: 6
NCURSES_VERSION_MINOR :: 5
NCURSES_VERSION_PATCH :: 20250216
NCURSES_VERSION :: "6.5"

NCURSES_MOUSE_VERSION :: 2


NCURSES_ATTR_SHIFT :: 8

COLOR_BLACK :: 0
COLOR_RED :: 1
COLOR_GREEN :: 2
COLOR_YELLOW :: 3
COLOR_BLUE :: 4
COLOR_MAGENTA :: 5
COLOR_CYAN :: 6
COLOR_WHITE :: 7
